services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
      - elasticsearch

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - API_URL=http://laravel_app:8000/api/v1
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  scheduler:
    build:
      context: ./backend
    container_name: laravel_scheduler
    volumes:
      - ./backend:/var/www
    command: php artisan schedule:work
    depends_on:
      - app
      - db
      - elasticsearch


volumes:
  db_data:
  es_data:
